(function(){
    'use strict';
  
    angular.module("app.membership").factory("memTerritoryService", memTerritoryService);
    
    /** @ngInject **/
    function memTerritoryService(firebaseDataRef, DataUtils, $q){
        var items = firebaseDataRef.child('membership-territories');
    
        var services = {
            getAllTerritoryLoadOnce: getAllTerritoryLoadOnce,
            create: create
        };
  
        return services;

        function getAllTerritoryLoadOnce(){
            return DataUtils.getListDataFirebaseLoadOnce(items);
        }

        function create(){
            var data = ["1.1.1 NW Ft Worth",
            "1.1.2 NE Ft Worth",
            "1.1.3 NW Dallas",
            "1.1.4 NE Dallas",
            "1.1.5 Grand Prairie",
            "1.1.6 S Ft Worth",
            "1.1.7 SE Dallas",
            "1.1.8 East Texas (NE)",
            "1.2.1 NW Houston",
            "1.2.2 NE Houston",
            "1.2.3 SW Houston",
            "1.2.4 SE Houston",
            "1.2.5 Katy/Brenham",
            "1.2.6 Conroe/Hunstville",
            "1.2.7 Beaumont/Port Arthur",
            "1.2.8 East Texas (SE)",
            "1.3.1 NW San Antonio",
            "1.3.2 NE San Antonio",
            "1.3.3 SE San Antonio",
            "1.3.4 SW San Antonio",
            "1.3.5 W Austin",
            "1.3.6 NE Austin",
            "1.3.7 SE Austin",
            "1.3.8 Victoria",
            "1.3.9 Laredo",
            "1.3.10 McAllen / Brownsville",
            "1.4.1 Abilene",
            "1.4.2 Midland / Odessa",
            "1.4.3 Amarillo",
            "1.4.4 Lubbock",
            "1.4.5 El Paso",
            "1.4.6 San Angelo South",
            "1.4.7 S.W. Mountains",
            "1.5.1 Waco",
            "1.5.2 Temple",
            "1.5.3 College Station",
            "2.1.1 North Georgia",
            "2.1.2 Central Georgia",
            "2.1.3 South Georgia",
            "2.1.4 Central East",
            "2.1.5 South West",
            "2.1.6 South East",
            "2.1.7 South Georgia",
            "3.1.1 Central",
            "3.1.2 North East",
            "3.1.3 South East",
            "3.1.4 South Central",
            "3.1.5 South West",
            "4.1.1 St. Louis (Surrounding)",
            "4.1.2 Kansas City (Surrounding)",
            "4.1.3 Springfield (Surrounding)",
            "4.1.4 SE MO",
            "4.1.5 NE MO",
            "5.1.1 Central Area",
            "5.1.2 South East",
            "5.1.3 West Area",
            "5.1.4 North East",
            "5.1.5 North",
            "6.1.1 N Denver/Boulder",
            "6.1.2 FT Collins/Loveland",
            "6.1.3 S Denver/Aurora",
            "6.1.4 Colorado Springs/Pueblo",
            "6.1.5 Grand Junction",
            "6.1.6 SW Colorado",
            "7.1.1 Richmond Metro",
            "7.1.2 South DC",
            "7.1.3 Norfolk",
            "7.1.4 Western & Other",
            "8.1.1 North West",
            "8.1.2 North Central",
            "8.1.3 North East",
            "8.1.4 East Central",
            "8.1.5 South West",
            "8.1.6 South East",
            "8.1.7 West Central",
            "9.1.1 North NJ",
            "9.1.2 Central NJ",
            "9.1.3 South NJ",
            "10.1.1 Kansas City / Topeka",
            "10.1.2 Wichita",
            "10.1.3 Salina / Junction City",
            "10.1.4 Dodge City / Liberal",
            "11.1.1 NW Ohio Toledo and Surrounding",
            "11.1.2 NE Ohio Akron and Surrounding",
            "11.1.3 East Ohio",
            "11.1.4 Central Ohio",
            "11.1.5 Southern Ohio Cincinnati / Dayton",
            "12.1.1 NW Arkansas",
            "12.1.2 NE Arkansas",
            "12.1.3 Central Arkansas",
            "12.1.4 South Arkansas",
            "13.1.1 Southwest",
            "13.1.2 Baltimore",
            "13.1.3 West",
            "13.1.4 East",
            "14.1.1 Central NC / Raleigh",
            "14.1.2 Charlotte",
            "14.1.3 East NC / Rocky Mount / Wilson / Goldsboro",
            "14.1.4 South NC / Wilmington",
            "14.1.5 Winston Salem / Greensboro",
            "14.1.6 West NC Asheville / Waynesville",
            "14.1.7 Boone / Morgantown / Shelby",
            "15.1.1 NW Washington",
            "15.1.2 SW Washington",
            "15.1.3 NE Washington",
            "15.1.4 SE Washington",
            "16.1.1 NW Oregon",
            "16.1.2 SW Oregon",
            "16.1.3 West Oregon",
            "17.1.1 Central California",
            "17.1.2 North California",
            "17.1.3 South California",
            "18.1.1 South Nevada",
            "18.1.2 West Nevada",
            "18.1.3 Central Nevada",
            "19.1.1 Central",
            "19.1.2 North",
            "19.1.3 South East",
            "20.1.1 NW Montana",
            "20.1.2 SW Montana",
            "20.1.3 Central Montana",
            "20.1.4 East Montana",
            "21.1.1 Southeast",
            "21.1.2 Northeast",
            "21.1.3 Southwest",
            "21.1.4 Northwest",
            "22.1.1 North",
            "22.1.2 South",
            "23.1.1 Central Arizona",
            "23.1.2 South / SE Arizona",
            "23.1.3 North Arizona",
            "24.1.1 South New Mexico",
            "24.1.2 North New Mexico",
            "25.1.1 East North Dakota",
            "25.1.2 West North Dakota",
            "26.1.1 East",
            "26.1.2 West",
            "27.1.1 Southeast",
            "27.1.2 South",
            "27.1.3 North",
            "27.1.4 West",
            "28.1.1 South Central",
            "28.1.2 East",
            "28.1.3 South",
            "28.1.4 West",
            "29.1.1 Southeast",
            "29.1.2 South Central",
            "29.1.3 Northeast",
            "29.1.4 Northwest",
            "29.1.5 Southwest",
            "30.1.1 Central Louisiana",
            "30.1.2 West Louisiana",
            "30.1.3 North Louisiana",
            "31.1.1 South (Milwaukee)",
            "31.1.2 East",
            "31.1.3 West",
            "32.1.1 Central Illinois",
            "32.1.2 North Illiniois",
            "32.1.3 South Central Illionis",
            "32.1.4 South Illinois",
            "33.1.1 Central (Nashville)",
            "33.1.2 South East (Chattanooga)",
            "33.1.3 West (Memphis)",
            "33.1.4 East (Knoxville)",
            "35.1.1 East (Detroit & Surrounding)",
            "35.1.2 South (Grand Rapids & Lansing)",
            "35.1.3 Central",
            "35.1.4 North (Upper Peninsula)",
            "36.1.1 Central Indiana",
            "36.1.2 North Indiana",
            "36.1.3 South Indiana",
            "37.1.1 Louisville",
            "37.1.2 Lexington",
            "37.1.3 South East",
            "37.1.4 Bowling Green",
            "37.1.5 Henderson & Owensboro",
            "38.1.1 Central Alabama",
            "38.1.2 North Alabama",
            "38.1.3 South Central Alabama",
            "38.1.4 South Alabama",
            "39.1.1 Southwest",
            "39.1.2 Southeast",
            "39.1.3 Northeast",
            "39.1.4 North",
            "40.1.1 Central (Columbia)",
            "40.1.2 North West (Greenville)",
            "40.1.3 East (Myrtle Beach)",
            "40.1.4 South (Charleston)",
            "47.1.1 South",
            "47.1.2 North",
            "51.1.1 East",
            "51.1.2 West"];
            var reqs = [];
            _.forEach(data, function(item){
                var key = items.push().key,
                    ref = items.child(key);
                reqs.push(ref.update({
                    id: key,
                    value: item,
                    name: item,
                }));
            });

            return $q.all(reqs);
        }
    }
  })();
  